### ISSUE TITLE
High latency in one direction only when connected to conference call

### ISSUE THREAD

**Issue by Oudalally** [sipsorcery-org/sipsorcery#1099]
We have a phone system running on Asterisk, with both a SipSorcery instance and a Cisco IP phone connecting to a conference call.

Audio from the softphone to the handset is sent with a minimal latency, and is working perfectly fine, however audio from the Cisco phone back to the softphone has a high latency. This was initially around 4 seconds, but adding a buffer reduced this to around 1 second. This is an improvement, but still too high.

Connecting 2 Cisco phones to the conference in the same way has no notable latency (there is some, but it's less than 100ms so nothing to be concerned about).

The implementation is using NAudio (via SipSorceryMedia.Windows), and a VoipMediaSession to handle the RTP as shown below.
Is there something I've missed here, or is this indicative of a bug?

```

audioEndpoint = new WindowsAudioEndPoint(encoder, outputDeviceIndex, inputDeviceIndex);

List<AudioFormat> sinkFormats = audioEndpoint.GetAudioSinkFormats();
List<AudioFormat> sourceFormats = audioEndpoint.GetAudioSourceFormats();


AudioFormat sourceAudioFormat = sourceFormats.FirstOrDefault(f => f.FormatName == "PCMA");
audioEndpoint.SetAudioSourceFormat(sourceAudioFormat);


AudioFormat sinkAudioFormat = sinkFormats.FirstOrDefault(f => f.FormatName == "PCMA");      
audioEndpoint.SetAudioSinkFormat(sinkAudioFormat);

MediaEndPoints endpoints = audioEndpoint.ToMediaEndPoints();
            
voipMediaSession = new VoIPMediaSession(audioEndpoint.ToMediaEndPoints());
voipMediaSession.AcceptRtpFromAny = true;
voipMediaSession.AudioExtrasSource.AudioSamplePeriodMilliseconds = 500;

TimeSpan packetTimeout = new TimeSpan(0, 0, 0, 40);
voipMediaSession.AudioStream.AddBuffer(packetTimeout);

```

**Comment by sipsorcery** [comment]
4s of latency sunds crazy high. That makes the audio essentially unusable, participants will be having different converstations. Once latency gets over 1s calls can get awkward.

This library, and it's siblings, focuses on signalling rather than media so I wouldn't claim it will give you an optimal audio experience. I recall a jitter buffer got added to one of the media libraries so the first thing I would do is turn that off. It's likely the only thing that could add 4s of latency. Personally I always perfer to have a few dropped packets instead of a jitter buffer.

**Comment by DavidMartynWood** [comment]
Naudio is a great library, but it is not designed for realtime audio. If you're using naudio's MediaFoundationResampler for example, it will inevitably build up 1 second of latency eventually. I suggest you look at your audio pipelines and see if excessive buffering could be occuring.

**Comment by sipsorcery** [comment]
If you think it's being caused by the NAudio settings the place to start is in the [SIPSorceryMedia.Windows code](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/blob/5b2367169cdffb1d870f025f2c5336b93bf59f63/src/WindowsAudioEndPoint.cs#L163).

If it was me the first thing I'd do is try and capture a WireShark trace of the call. It's good at showing jitter. That should at least give you an indication of whether it's the network or the application that's the likely cause.
