### ISSUE TITLE
Poor Audio Quality with SendAudioFromStream

### ISSUE THREAD

**Issue by babawarrior** [sipsorcery-org/sipsorcery#1215]
Hello,

I'm experiencing very poor audio quality when using 
```
voipMediaSession.AudioExtrasSource.SendAudioFromStream(new FileStream("hellowelcome8k.raw", FileMode.Open), AudioSamplingRatesEnum.Rate8KHz);
```

The audio on the call is almost unintelligible I can barely hear the first word, and the quality quickly deteriorates from there.

I'm using the sample audio file from the examples provided, and when I make a call using the same SIP credentials on MicroSIP, the audio is flawless with no lag. However, when calling via SIPSorcery.NET, the audio quality is severely degraded.

Is there any way to resolve this issue? Any help would be greatly appreciated!

**Comment by sipsorcery** [comment]
I can replicate this. I'm pretty sure it's a bug in the [VoIPMediaSession ctor](https://github.com/sipsorcery-org/sipsorcery/blob/39896a2b9e6eae66ba27b3d15bceec320f623f5a/src/app/Media/VoIPMediaSession.cs#L125). The  two lines below are resulting in duplcate event handlers that send the same audio sample twice.

```
 _audioExtrasSource.OnAudioSourceEncodedSample += SendAudio;
...
 Media.AudioSource.OnAudioSourceEncodedSample += SendAudio;
```

Commenting one of the lines OR initialising the class with a new AudioExtrasSource resulted in clean audio for me. THe same thing happens in two different ctors so if you try and it doesn't fix it double check it was the right ctor.

Once that's done the call below is able to play a clean audio file on my call:

`await rtpSession.AudioExtrasSource.SendAudioFromStream(new FileStream(WELCOME_8K, FileMode.Open), AudioSamplingRatesEnum.Rate8KHz);`

I'll work on a fix as time permits. It's been 4 years since I was worked on this code so I need to go voer what's changed in the inetervening period to try and avoid introducing a different bug.

**Comment by babawarrior** [comment]
> I can replicate this. I'm pretty sure it's a bug in the [VoIPMediaSession ctor](https://github.com/sipsorcery-org/sipsorcery/blob/39896a2b9e6eae66ba27b3d15bceec320f623f5a/src/app/Media/VoIPMediaSession.cs#L125). The two lines below are resulting in duplcate event handlers that send the same audio sample twice.
> 
> ```
>  _audioExtrasSource.OnAudioSourceEncodedSample += SendAudio;
> ...
>  Media.AudioSource.OnAudioSourceEncodedSample += SendAudio;
> ```
> 
> Commenting one of the lines OR initialising the class with a new AudioExtrasSource resulted in clean audio for me. THe same thing happens in two different ctors so if you try and it doesn't fix it double check it was the right ctor.
> 
> Once that's done the call below is able to play a clean audio file on my call:
> 
> `await rtpSession.AudioExtrasSource.SendAudioFromStream(new FileStream(WELCOME_8K, FileMode.Open), AudioSamplingRatesEnum.Rate8KHz);`
> 
> I'll work on a fix as time permits. It's been 4 years since I was worked on this code so I need to go voer what's changed in the inetervening period to try and avoid introducing a different bug.

Thank you so much. This helped me alot.
I commented out this:
`//_audioExtrasSource.OnAudioSourceEncodedSample += SendAudio;`
Now it works with perfect audio. Have a wonderful day.

**Comment by sipFan** [comment]
> I can replicate this. I'm pretty sure it's a bug in the [VoIPMediaSession ctor](https://github.com/sipsorcery-org/sipsorcery/blob/39896a2b9e6eae66ba27b3d15bceec320f623f5a/src/app/Media/VoIPMediaSession.cs#L125). The two lines below are resulting in duplcate event handlers that send the same audio sample twice.
> 
> ```
>  _audioExtrasSource.OnAudioSourceEncodedSample += SendAudio;
> ...
>  Media.AudioSource.OnAudioSourceEncodedSample += SendAudio;
> ```
> 
> Commenting one of the lines OR initialising the class with a new AudioExtrasSource resulted in clean audio for me. THe same thing happens in two different ctors so if you try and it doesn't fix it double check it was the right ctor.
> 
> Once that's done the call below is able to play a clean audio file on my call:
> 
> `await rtpSession.AudioExtrasSource.SendAudioFromStream(new FileStream(WELCOME_8K, FileMode.Open), AudioSamplingRatesEnum.Rate8KHz);`
> 
> I'll work on a fix as time permits. It's been 4 years since I was worked on this code so I need to go voer what's changed in the inetervening period to try and avoid introducing a different bug.

I have been working on a version of this that can take streams of unknown length and pipe it through to audio encoder. For use with TTS services streaming back their http response.  I have taken a worker task approach to avoid the need to deal with the timer synchronization.  If you'd like I can save you some time and submit PR in next week or two!  Love your library and want help out more !

**Comment by sipsorcery** [comment]
@sipFan a TTS media source sounds very nice. There have been a few requests for that and particularly recently where there seems to be a lot of interest in hooking up to the ChatGPT type LLM's.

If you are going to submit a PR it's be even better if it was a new class rather than adding more logic to something like VoiPMediaSession, which is already becoming unweildy.

**Comment by f2calv** [comment]
@babawarrior why did you close this as completed when the double event wire-up is still there?
