### ISSUE TITLE
Add support for WebRTC session re-negotation

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery-org/sipsorcery#352]
As per the [Session Negotiation Model](https://w3c.github.io/webrtc-pc/#session-negotiation-model).

Also see https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/ for additional context.

**Comment by cristianmad** [comment]
Hi, 

Are there any plans to support re-negotiation? One of our projects switched to a model where re-negotiations do happen and, after a few hours of debugging, I found this post :) 

Thank you,
Cristian

**Comment by sipsorcery** [comment]
It's certainly a desired feature and is on the radar. As far as a likely timeframe I don't have one at the moment.

**Comment by cristianmad** [comment]
ok, thank you!

**Comment by dennybm** [comment]
Hey @cristianmad 

Did you have a go at implementing the re-negotation? I'll be trying myself soon so just want to check if it was possible.

Thanks,
Denny

**Comment by cristianmad** [comment]
Hi Denny, 

I did not. In the end I had to switch to using the Mixed Reality WebRTC lib. I think that someone has already imlemented some support for media re-negotiation for sipsorcery, however the part that is missing is the ability to have multiple tracks of the same kind in one session. For example, in my case, I need to be able to add/remove audio and video tracks (more than 1 for each type) without having to tear down and re-establish the RTCPeerConnection. 

Unless it has recently been added, as far as I could tell, sipsorcery only supports a single track of each type per connection (up to 1 audio and 1 video track). The re-negotiation might work if you want to update those existing tracks, but not add new ones (in order to have more than 1 audio track for example).

**Comment by ChristopheI** [comment]
Hi @dennybm ,
Hi @cristianmad ,

Please check a look to this thread #708 and this branch [Use_Multi_AudioStream_or_VideoStream](https://github.com/ChristopheI/sipsorcery/tree/Use_Multi_AudioStream_or_VideoStream)

I have added support of Multi-Audio Stream and Multi-Video Stream. I detailed in #708 how I managed.

**Comment by lukedukeus** [comment]
@ChristopheI Is there any docs on how to do re-negotiation or is it still not supported? I get the onnegotiationneeded raised when I add a track, just not sure how to do re-negotiation.

Thanks!
