### ISSUE TITLE
Audio  Quality AudioSendOnlyMediaSession vs VoIPMediaSession

### ISSUE THREAD

**Issue by svaza** [sipsorcery-org/sipsorcery#404]
Hi,

Thank you for this awesome library !!!.
I am using this library for making SIP audio calls, SIP call is made to a PSTN number via SIP trunk (provided by a 3rd party vendor)

I notice there is a huge difference in audio quality when i use VoIPMediaSession and AudioSendOnlyMediaSession.
I use AudioSendOnlyMediaSession because i am running this application in linux docker container. VoIPMediaSession routes audio via speakers and mic, which are not available in linux docker.

When i use AudioSendOnlyMediaSession there is a lot of noise compared to VoIPMediaSession.
Can you suggest me a way to make it run on a docker container with near same audio quality as VoIPMediaSession ?

Thank you

**Comment by sipsorcery** [comment]
Most likely you're encountering the resolution of the .NET Core `Timer` class. The `Timer` resolution is likely to be further impacted by running on top of Docker. Have a read of this #66 for a relevant discussion. A [comment](https://github.com/sipsorcery-org/sipsorcery/issues/66#issuecomment-757359545) in that issue does mention an improvement by using a 3rd party package for the timing source but I haven't tested it.

**Comment by bergqvm** [comment]
Hi!
I have made a breakout example of the code attached. Since I wanted to keep the existing classes intact for testing purposes I made a HighPrecisionAudioSource and HighPrecisionVoipMediaSession that relies on the MicroTimer library.

[HighPrecisionTimerExample.txt](https://github.com/sipsorcery-org/sipsorcery/files/5882547/HighPrecisionTimerExample.txt)

**Comment by sipsorcery** [comment]
Any future work on this feature can be done in #471.
