### ISSUE TITLE
Can I convert RTSP to WebRTC?

### ISSUE THREAD

**Issue by imnotcode** [sipsorcery-org/sipsorcery#408]
I tried converting the RTSP protocol to Raw Image and encoding it with ffmpeg, but it used too much CPU resources.

So, I want to send H.264 Frame directly to RTCPeerConnection.SendVideo() in SIPSorcery.

Is it possible?

If it is possible, how can I get H.264 Frame from RTSP?

**Comment by sipsorcery** [comment]
Yes it's possible.

This [demo program](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/WebRTCExamples/SIPToWebRtcBridgeVideo/Program.cs) does exactly the same thing but for SIP instead of RTSP. You could use it as a starting point and replace the SIP logic with your RTSP client logic.

> If it is possible, how can I get H.264 Frame from RTSP?

That will depend on the RTSP client you're using. Note I'd advise against using the RTSP classes in the sipsorcery library, they have had zero attention and testing for a number of years.

**Comment by imnotcode** [comment]
I succeeded in sending RTP directly to WebRTC thanks.

**Comment by sinhngoc2008** [comment]
> I succeeded in sending RTP directly to WebRTC thanks.

Can you share a little bit about sending RTP samples to webrtc ?

**Comment by imnotcode** [comment]
> > I succeeded in sending RTP directly to WebRTC thanks.
> 
> Can you share a little bit about sending RTP samples to webrtc ?

I can't share the code directly, but I'll share my experience.

I literally did SIP instead of RTSP.

Implement the entire RTSP directly or use a library to decompose the protocol to find the RTP Packet.

And then, send the payload to SendRtpRaw. 

Alternatively, you can decompose the packet further to find the H.264 payload and send SPS and PPS to SendVideo.
