### ISSUE TITLE
Question: preview versions

### ISSUE THREAD

**Issue by LADSoft** [sipsorcery-org/sipsorcery#410]
A lot of the components are in preview right now, including both Sipsorcery and the SipSorcery/windows media as well as a dns component.   AFAICT the sipsorcery/windows media has never been out of preview.

Any plans for when all of this will be out of preview and be regular releases?

**Comment by sipsorcery** [comment]
Yes, fair question, but sadly no easy answer.

Late in 2019 the plan was to release a stable version of the main `SIPSorcery` library when it was "ready" within 3 to 6 months. But at that time there were was no WebRTC, no media integration and only a very poor RTP implementation. Since WebRTC got added the "ready" status just seems to be getting further and further away.

Leaving WebRTC aside when the next stable version of [DnsClient.Net](https://github.com/MichaCo/DnsClient.NET) is released I would anticipate doing another stable release of the main `SIPSorcery` library. I did help make some changes to that DNS library so it was better suited for VoIP scenarios and that are relied on, hence the current dependency on a beta version.

As for the SIPSorcery Media libraries it's even less clear. I'd definitely like to stabilise the interfaces and generic logic in [SIPSorceryMedia.Abstractions](https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions) but for the other assemblies I'm not sure what their future will be. 

For example if the VP8 encoder is ever successfully ported, either in [VP8.Net](https://github.com/sipsorcery-org/VP8.Net) or some other port, then it would feasibly replace [SIPSorceryMedia.Encoders](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders). For the other two, [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg) and [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows), I don't know where they'll end up. I tend to work on them as I need things for demo apps and don't test them anywhere near as extensively as the main library.

**Comment by LADSoft** [comment]
thanks!
