### ISSUE TITLE
Send PUBLISH

### ISSUE THREAD

**Issue by ilogixxDE** [sipsorcery-org/sipsorcery#418]
Is it possible to publish the presence of a ua with this library. I can't find a hint, so can you please point me in the right direction.

Thanks

**Comment by sipsorcery** [comment]
The short answer is no. [RFC 3856: A Presence Event Package for the Session Initiation Protocol (SIP)](https://tools.ietf.org/html/rfc3856) is not implemented.

The longer answer is that there was a level of support for a tweaked version of that RFC in an earlier version of this library.  For example this [class](https://github.com/sipsorcery-org/sipsorcery/blob/9ecaafb996a9d5ab4deccb22fa241c8acf5f0ab5/sipsorcery-core/SIPSorcery.SIP.App/SIPNotifications/SIPPresenceEventSubscription.cs) was used to build the presence records for a SIP account. And the library even used to include the [XML Schema document](https://github.com/sipsorcery-org/sipsorcery/blob/9ecaafb996a9d5ab4deccb22fa241c8acf5f0ab5/sipsorcery-core/SIPSorcery.SIP.Core/SIPEvents/Presence/PIDFSchema.xsd) in order to validate SIP event presence payloads. Other than that I've never gotten around to implementing presence notifications. To be honest in all my time using SIP the only SIP events I've ever found to be useful are Message Waiting Indications (MWI) for voicemail. But of course for some scenarios presence, dialog and other events may be very useful; call centers are probably one such case.

**Comment by ilogixxDE** [comment]
We are in the Teco industrie since a long time, and one of the most asked questions is about presence and presence synchronisation with other systems like teams. So I does not know one system that does not use presence so here in Germany or Europe this is a major feature in SIP. Maybe we should think about a clean implementation of rich presence. I will see if my team can do something in that area.

**Comment by dv8inpp** [comment]
ilogixxDE thanks for asking that question as I am also be interested in this functionality. As more people work remotely it would be nice to know from their phones what they are doing at this moment. Are they Online, Offline, Away, Busy, On the phone, Out to lunch or will they 'be right back'.

**Comment by sipsorcery** [comment]
Feel free to re-open if anything else can be done.
