### ISSUE TITLE
Transcoding H264 for use in MS Graph Comms Media SDK

### ISSUE THREAD

**Issue by vbsteven** [sipsorcery-org/sipsorcery#459]
Hello, 

I'm trying to use SipSorcery to bridge a WebRTC PeerConnection to a MS Teams bot using the MS Graph Comms Media SDK. 

On the SipSorcery side I have the WebRTC PeerConnection set up and the `peerConnection.OnVideoFrameReceived` callback is triggered with the H264 buffers (or VP8 which my sending end also supports, it's an Android app using Google WebRTC libs). 

on the Graph Comms Media SDK side (I'm using their AudioVideoPlaybackBot example) I need to prepare the VideoSendBuffer so i can call `audioVideoFramePlayer.EnqueueBuffersAsync()` with the received frames. 

What I'm struggling with right now is how to convert the raw buffer from `OnVideoFrameReceived` to a  `VideoSendBuffer` that Graph Comms Media SDK accepts.

The Graph Comms Media SDK seems to require multiple output resolutions so I'll probably need some transcoding on the fly to convert my incoming (1280x720 H264) frames to the formats that GraphComms expects 
```
VideoFormat.H264_1280x720_30Fps,
VideoFormat.H264_640x360_30Fps,
VideoFormat.H264_320x180_15Fps,
```

Have you already experimented with something like this? Could you point me in a certain direction on how this should/could be done?

**Comment by sipsorcery** [comment]
I did so some similar work previously but for an audio only SIP call rather than an Android WebRTC call.

My advice would be to see if you can get an audio only call working first and then move onto video. It's hard enough getting anything to do with Teams Bot working so starting simple is a good idea. Also just in case you haven't see it there is the newer [Azure Communications Service](https://docs.microsoft.com/en-us/azure/communication-services/) which supposedly has an SDK for iOS and Android that can place calls to Teams.

If you do continue down the path of using the sipsorcery library in your bot the trick is to use the audio packets and video frames without doing any decoding or encoding. To do that you can hook the `OnRtpPacketReceived` and `OnVideoFrameReceived` events:

````
rtpSession.OnRtpPacketReceived += ForwardAudioToPeerConnection;
rtpSession.OnVideoFrameReceived += ForwardVideoFrameToPeerConnection;
````

The [SIPToWebRTCBridgeVideo](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/SIPToWebRtcBridgeVideo) is probably the closest example.

> so I'll probably need some transcoding on the fly to convert my incoming (1280x720 H264) frames to the formats that GraphComms expects

If you do need to do any kind of transcoding or video processing the task gets a lot more difficult and depending on how scalable your Bot needs to be .NET may not be the best solution. Alternatives could be a C++ app using `gstreamer` or `libwbertc`.

**Comment by vbsteven** [comment]
Thank you for taking the time to answer.

I'm going to check out the Azure Communications SDK's in parallel because they might be able to do what I need. 

Right now I'm in the PoC stage so I just want to get something working. I'm going to experiment a bit with the TestPatternVideoSource to see if I can feed that into my GraphComms, and if that works figure out how to do a remote stream from Android.

**Comment by vbsteven** [comment]
A small update on my testing: I managed to get video through to an MS Teams meeting by :

* switching my Android client to use VP8
* hooking `peerConnection.OnVideoFrameReceived`
* in `OnVideoFrameReceived` run the frame byte[] through `Vp8Codec.Decode()` 
* use `PixelConverter.I420toRGB()` to get an RGB24 frame
* then wrap the RGB24 frame into a MS Graph Media SDK `VideoSendBuffer` with an RGB24 video format
* send the videoSendBuffer over the Media SDK main video socket (that is configured to accept RGB24 with my width/height)

It's far from optimal but at least now I have a happy path working and I can iterate further.

Thank you for your work on SipSorcery. The library is a joy to work with and was super easy to hook up to my custom signaling protocol.

**Comment by sipsorcery** [comment]
Nice work! And of course I was wrong in my comment above about avoiding the video/encode decode stage. I overlooked the fact that the Bot framework only takes raw audio/video samples.

Sadly Microsoft seem to have a big disconnect between their teams for real-time communications and .NET. Microsoft Teams, which seems to have at least some of the Skype components, uses WebRTC under the hood but when it comes to a .NET Teams API or .NET Azure Communications Services API (which can get media to Teams) it all seems too hard :(

https://github.com/Azure/Communication/issues/37
https://github.com/Azure/Communication/issues/72

Of course it'd be even better if Microsoft added some basic real-time comms components to .NET but apart from [wrapping](https://github.com/microsoft/MixedReality-WebRTC) `libwebrtc` there's very little interest. And even projects that purport to [expose](https://github.com/microsoft/winrtc) `libwebrtc` for use with .NET seem to peter out very quickly.

Rant over.
