### ISSUE TITLE
Is this Library designed to develop an Client/Server structure?

### ISSUE THREAD

**Issue by TheRealLenon** [sipsorcery-org/sipsorcery#502]
Is this Library designed to only accept Peer-to-Peer connections, or can we build an client/server architecture on it?

Referencing to [this](https://github.com/sipsorcery-org/sipsorcery/issues/465) related Issue, I was wondering, if this is only related to the **SIPClient** or for the general library.

The behavior would be the following:
1. Server started and listening for clients & voice data
1.2 Server receives voice data and broadcasts it to all connected clients
2. Clients connect to the server
2.1 Clients Sending their voice data to the server
2.2 Clients receive voice data from the Server

**Comment by sipsorcery** [comment]
> Is this Library designed to only accept Peer-to-Peer connections, or can we build an client/server architecture on it?

It can do both. The original motivation for the library was the need for a SIP Proxy serving SIP Client User Agents.

Most of the examples are for clients since that's the more popular use case. The best server example is the [signalrtc](https://github.com/sipsorcery-org/signalrtc) application. It might not suit your exact needs since it does not process the audio streams. It does act as a B2B User Agent where the media is transferred directly between the two call participants.

If you need to combine audio from multiple sources be aware that this library does not have any mixing capabilities. If you only need to duplicate a single source stream to multiple clients it can do that.

**Comment by TheRealLenon** [comment]
I´m not aware, what you mean 

by 

> does not have any mixing capabilities. If you only need to duplicate a single source stream to multiple clients

Let me may explain further:
The clients should all receive the voice data which gets broadcasted to them. When multiple clients are talking it should be like any other VoIP-Application like Skype, Teams, TeamSpeak or Discord where it´s just multiple people talking and you don´t understand a word.

**Comment by sipsorcery** [comment]
This is a [good article](https://www.frozenmountain.com/hubfs/5%20-%20pdfs/frozenmountain-mcu-multipoint-control-unit-whitepaper.pdf) on audio/video mixing. The article is about WebRTC but the media mixing concepts are the same for SIP.

If you don't actually need to support existing SIP clients or hardware IP Phones you should consider using WebRTC. And in which case you should look at using one of the many existing products that can provide the building blocks for your app, see Jitsi, Janus, Kurento etc.

**Comment by TheRealLenon** [comment]
I´ll take a look at this! Thank you! :)
