### ISSUE TITLE
VP9 Library

### ISSUE THREAD

**Issue by Terricide** [sipsorcery-org/sipsorcery#505]
I'm not sure if this is useful or not but I think this might be a full VP9 decoder written in c# that you might find interesting.

https://github.com/Ryujinx/Ryujinx/tree/master/Ryujinx.Graphics.Nvdec.Vp9

**Comment by sipsorcery** [comment]
Damn, I wish I'd seen that last November before I spent a month working on the same thing. I'm sure their implementation works better than mine.

It doesn't look like they'll ever need an encoder in that project. That's currently the missing bit.

**Comment by Terricide** [comment]
I was thinking that the code might show some lower level performanxe tricks that could be used in an encoder. But I was surprised when I stumpled on it and it wasnt just a wrapper.

**Comment by rafcsoares** [comment]
I already tried to implement H264 in a pure C# and i think that the encoder will never perform well as in native C++ because of micro-otimization per platform type that can drastically improve the performance. 

I dropped my solution when o saw the performance diference between native c++ dll and my encoder c# version.

For decoder the performance diference is around 3-5 times slower... for encoder, more than 20 times, unfortunally.

**Comment by rafcsoares** [comment]
Okey, i checked out the code and inside the class FfmegContext a process was called searching for ffmpeg inside your computed.

So, this is a wrapper for ffmpeg process inside windows and not an C# pure implementation.

```
static FFmpegContext()
        {
            SetRootPath();
        }

        private static void SetRootPath()
        {
            if (OperatingSystem.IsLinux())
            {
                // Configure FFmpeg search path
                Process lddProcess = Process.Start(new ProcessStartInfo
                {
                    FileName               = "/bin/sh",
                    Arguments              = "-c \"ldd $(which ffmpeg 2>/dev/null) | grep libavfilter\" 2>/dev/null",
                    UseShellExecute        = false,
                    RedirectStandardOutput = true
                });

                string lddOutput = lddProcess.StandardOutput.ReadToEnd();

                lddProcess.WaitForExit();
                lddProcess.Close();

                if (lddOutput.Contains(" => "))
                {
                    ffmpeg.RootPath = Path.GetDirectoryName(lddOutput.Split(" => ")[1]);
                }
                else
                {
                    Logger.Error?.PrintMsg(LogClass.FFmpeg, "FFmpeg wasn't found. Make sure that you have it installed and up to date.");
                }
            }
        }

```

**Comment by sipsorcery** [comment]
> I already tried to implement H264 in a pure C# and i think that the encoder will never perform well as in native C++ because of micro-otimization per platform type that can drastically improve the performance.

My hope was that the C# VP8 version would perform well enough for a basic/standard use case, for example 640x480@30fps. And even if that didn't workout there are still likely to be situations where lower frame rates and/or resolutions are acceptable (320x240@10fps) and the ease of a .NET library cross platform deployment outweighs the hassle of multiple native libraries. I think this is more likely to be the case on mobile for Xamarin/MAUI apps and for Unity3D apps.

The pure C# VP8 decoder that I got working was buggy and not performant but it was able to decode a few frames which proves it is possible.

I suspect that given enough time and resources a C# VP8 encoder and decoder capable of 640x480@30fps is achievable, Unfortunately in my case my window of opportunity to work on it has now closed for the foreseeable future.

**Comment by Terricide** [comment]
Do you have the source code for the h264 c# version? I wonder if using Hardware Intrinsics, things like Span, Memory<T> could drastically speed it up?

**Comment by rafcsoares** [comment]
@Terricide I have the source but I unable to share it as open-source because of license problems with my employer.

Inside the code, I already use byte* to improve the performance.

Inside my benchmarks the Span<byte>/ArraySegment<byte>/Memory<byte> does not perform as well as byte[] and byte*.

byte* and byte[] can be optimized in compile-time inside iterations.

Some micro-optimizations in C# can double-up speed of iterations inside quantization/dequantization logics

```
int length = array.Length;
for(int i=0; I<length; i++) {
 }
```
instead

```
for(int i=0; I<array.Length; i++) { 
}
```

but the performs is not even close as C++ wrapper
