### ISSUE TITLE
PortAudio example issue

### ISSUE THREAD

**Issue by Rok-P** [sipsorcery-org/sipsorcery#546]
Hello, First of all, impressive work!

I am playing around with the PortAudio example and I have problem getting the sound working. I'm using NetCore on Linux and the last version of SipSorcery from GitHub.

PortAudio captures default devices fine. The UPD packets come in with no problems. I can see AudioEncoder doing its job and I can follow the packet information up to PortAudioEndPoint.GotAudioRtp. But after that nothing gets triggered and I believe no info is sent to the media stream. The PortAudioDevicePump objects sees no movement (neither OnStreamData or WriteAudioFrame that should call ReadAudioDataCalback). The DataTask in PortAudioDevicePump is running and gets terminated when the remote party hangs up.

I did have to make a change to PortAudioDevicePump.WriteAudioFrame. I made it not to call ReadAudioDataCalback when called by Pump's constructor - the ReadAudioDataCalback blocks at _remoteSampleReady.Wait() since the program is still on main thread.

The input device seems to work, even though at the other end I can only hear static (could be encoder issue?). So, for now I disabled the input device.

I’m kind of stuck at this point. I did notice that this example is 6 months old, so I am wondering should I try an older (maybe 5.1) version?

**Comment by sipsorcery** [comment]
> I’m kind of stuck at this point. I did notice that this example is 6 months old, so I am wondering should I try an older (maybe 5.1) version?

No, I don't think so, the problem is not likely to be with the main sipsorcery library but with the PortAudio specific logic in the example.

It was a battle to get PortAudio working with .Net Core on my Ubuntu machine at the time and involved a lot of trial and error. I've just tested the example again on the same machine and it no longer works. I'm using a different monitor which I suspect has changed the audio config. I mucked around for a bit but couldn't get fix it.

There are some notes at the top of `Program.cs` about using `PortAudio` on Linux, they might help with troubleshooting. The `pactl` command was what I was messing around with. The fix is likely to be something with either the PortAudio install/setup or something in `PortAudioEndPoint.cs`.

On the other hand if you know of a better library for working with .NET and audio on Linux it might be wroth replacing the `PortAudioEndPoint.cs` class with a new implementation. It's never worked that well.

**Comment by Rok-P** [comment]
Thank you for the answer!
I was suspecting PortAudio could be the issue here. I compiled it from github and the provided tests worked fine. In `LinuxLibraryLoader` I had to change the LIBDL to call `libportaudio.so.2.0.0`. I used it as standalone and installed on the system with same results. Will also use the described approach with `libdl` on a WM and see how that goes. If I make any progress, I'll post it here.
Never did much work on media on any platform before, but I guess this could be a nice side project.
