### ISSUE TITLE
_sipTransport.Shutdown() doesn't unregister the extension

### ISSUE THREAD

**Issue by finebytes** [sipsorcery-org/sipsorcery#562]
The extension remains registered when I call Shutdown()
It happens even if I call _sipRegistrationUserAgent.Stop(); before.
Unfortunately the pbx we're using, even though allows multiple registrations for the same extension only sends the INVITE session to the first registration. So essentially after a disconnect, even if you register back, you won't get any calls.

Is there something I'm doing wrong?
![image](https://user-images.githubusercontent.com/595559/132814030-2c8aa06a-f012-4306-8663-8e435ac73d17.png)

**Comment by sipsorcery** [comment]
Yes, you need to put a delay in between stopping the registration agent and shutting down the transport.

When the registration agent stops it needs to send a `REGISTER` request with a 0 expiry in order to tell the server it's no longer available. You need to give the SIP transport a second or so to send that request.

**Comment by finebytes** [comment]
That actually worked really good.

**Comment by finebytes** [comment]
Added a PR, to have that in the examples section
https://github.com/sipsorcery-org/sipsorcery/pull/563

Thanks!
