### ISSUE TITLE
Fix github.io URL in Wiki

### ISSUE THREAD

**Issue by pkolmann** [sipsorcery-org/sipsorcery#589]
Hi,

while working with your project, we saw, that in the Wiki it seems to be an old(?) url to the github.io pages (-org is missing):

https://github.com/sipsorcery-org/sipsorcery/wiki

Can you please update the url within the wiki to the proper URL:

https://sipsorcery-org.github.io/sipsorcery

Thanks
Philipp

**Comment by sipsorcery** [comment]
Hi Philipp,

Thanks for the suggestion. I'm leaving the wiki around for sentimental
reasons.

The first section on the Wiki home page does already have the link to the
github pages site in order to avoid confusion.

The Wiki Content is from when this project was imported from CodePlex
(which for youngsters was Microsoft's free open source code repository
before they bought GitHub...). Since the import this project has evolved
substantially and the reference documentation is now available at
https://sipsorcery.github.io/sipsorcery/. This Wiki Content is kept around
for posterity.

Regards,
Aaron

**Comment by pkolmann** [comment]
@sipsorcery This is exactly the issue. In the first paragraph it seems that an old URL was used and it changed sometime in the past. I was looking first into the wiki and tried the link https://sipsorcery.github.io/sipsorcery/ but this gives me a 404.

It would help new users to find the proper documentation if you update exactly this link to https://sipsorcery-org.github.io/sipsorcery/

thanks

**Comment by sipsorcery** [comment]
Ah, I missed that. I've fixed the link now. Thanks for letting me know.
