### ISSUE TITLE
 There is no async version of OnIncomingCall event

### ISSUE THREAD

**Issue by nserj** [sipsorcery-org/sipsorcery#647]
OnIncomingCall event will be called from **async Task SIPTransportRequestReceived**. Is there any reasons that OnIncomingCall  is not async please?

**Comment by sipsorcery** [comment]
The thread that fires the `SIPTransportRequestReceived` event is the thread that listens for incoming messages on that particular SIP channel. The `OnIncomingCall` event should not be doing anything long running or you'll ned up causing the underlying SIP channel to become unresponsive. The reason here is no async method is to encourage you to do what you need to do quickly or to get onto a different thread.
