### ISSUE TITLE
Exception when using AudioSendOnlyMediaSession

### ISSUE THREAD

**Issue by boskjoett** [sipsorcery-org/sipsorcery#677]
When I use an AudioSendOnlyMediaSession as media session for a call with a SIPUserAgent I get this exception

Unhandled exception. System.ArgumentNullException: Value cannot be null.
    at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
    at SIPSorcery.Media.AudioExtrasSource.SendMusicSample(Object state)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
 --- End of stack trace from previous location ---
    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
    at System.Threading.TimerQueue.FireNextTimers()
    
It seems that this exception only occurs when running on a Linux (Ubuntu) OS. I have not seen it on a Windows host.
What could cause this exception? Which value is it that cannot be null?

**Comment by sipsorcery** [comment]
Can you include the relevant part of your program? My guess would be there's a problem accessing the music file.

**Comment by easycaller-edossantos** [comment]
I'm having the same issue, but while sending silence instead of music:
Unhandled exception. System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at SIPSorcery.Media.AudioExtrasSource.SendSilenceSample(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


According to the stack thread, this happens inside AudioExtrasSource, on line 432, when the library tries to lock the Timer object:
lock (_sendSampleTimer)

In this case, somehow _sendSampleTimer is null, and this causes the issue.

Reviewing the code, I don't see how this Timer object can become null. Actually, it's never being set to null, it might be disposed, but not set to null. Not sure if this might give you some pointers. I've been checking the code for hours, but not getting how this might happen.... I will continue investigating and let you know if I find anything else.

**Comment by easycaller-edossantos** [comment]
Here's a piece of code that eventually reproduces the issue:
`
    private VoIPMediaSession CreateRtpSession()
    {
        var codecs = new List<AudioCodecsEnum>
        {
            AudioCodecsEnum.PCMU,
            AudioCodecsEnum.PCMA,
            AudioCodecsEnum.G722,
            AudioCodecsEnum.G729
        };

        var audioExtrasSource = new AudioExtrasSource(
            new AudioEncoder(),
            new AudioSourceOptions { AudioSource = AudioSourcesEnum.Silence }
        );
        audioExtrasSource.RestrictFormats(formats => codecs.Contains(formats.Codec));
        var rtpAudioSession = new VoIPMediaSession(
            new VoIPMediaSessionConfig()
            {
                MediaEndPoint = new MediaEndPoints { AudioSource = audioExtrasSource }
            }
        )
        {
            AcceptRtpFromAny = true
        };

        return rtpAudioSession;
    }

    public void Accept(SIPRequest sipRequest)
    {
        _uas = _ua.AcceptCall(sipRequest);
    }

    public async Task AnswerCall()
    {
        if (_uas is null)
            throw new Exception("Call has not been accepted");

        var rtpSession = CreateRtpSession();
        await _ua.Answer(_uas, rtpSession);

        if (_ua.IsCallActive)
            await rtpSession.Start();
    }
`

The member _ua is built as:
`_ua = new SIPUserAgent(_sipTransport, null);`

And the _sipTransport is built using the default constructor.

When an inbound call arrives, we invoke `Accept` first, and a few seconds later (between 2 and 15 seconds), we invoke `AnswerCall`. At this point the app crashes. This is not happening for every call, but in our case we usually reproduce it after 10 or 20 calls.

This also happens making outbound calls.

Do you see anything wrong in the code we use?

**Comment by easycaller-edossantos** [comment]
@sipsorcery this issue should be closed as it's fixed by pull request #1011.
BTW, is it possible to get this published via nuget?
