### ISSUE TITLE
G729 encode problem

### ISSUE THREAD

**Issue by z791382465** [sipsorcery-org/sipsorcery#707]
I use sipsorcery to answer a sip audio call with G729 codec.
On sipsorcery side listen audio normally, but on caller side hear the noise(can hear volume change on speaking).

**Comment by z791382465** [comment]
https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/blob/master/src/WindowsAudioEndPoint.cs#L280
`OnAudioSourceEncodedSample?.Invoke((uint)encodedSample.Length, encodedSample);`

Follow this code the first parameter will be 20, but it shold be 160.
Maybe can fix like this, but i think this is not a good solution.
`OnAudioSourceEncodedSample?.Invoke((uint)_audioFormatManager.SelectedFormat.RtpClockRate / 1000 * AUDIO_SAMPLE_PERIOD_MILLISECONDS, encodedSample);`

**Comment by ChristopheI** [comment]
hi @z791382465 ,

Which library are you using to Encode / Decode sound ?
Which library are you using to manage Audio Input and Audio Output ?

**Comment by ChristopheI** [comment]
I never used SIPSorceryMedia.Windows.WindowsAudioEndPoint.

I created recently a new package [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2) which should work with G729

I'm sure this library is working with PCMU (G711), PCMA (G711), G722 and Opus since I have tested them in a real WebRTC context. (using Edge / Chrome browser as remote peer - the sound was good in both direction)

G729 is not used in WebRTC context so I cannot test it in real context.  I have just tested it using an Audio Input source (from a file or a Microphone) then I encode it and decode it to finally check the result in an Audio Output

**Comment by z791382465** [comment]
Thank you for your help.
Sorry, I should definition my problem correctly.

SIPSorcery.Media.AudioEncoder is working.
I think SIPSorceryMedia.Windows.WindowsAudioEndPoint use wrong parameter to play decoded G729 audio.

**Comment by z791382465** [comment]
Thank you for your help.
Sorry, I should definition my problem correctly.

SIPSorcery.Media.AudioEncoder is working.
I think SIPSorceryMedia.Windows.WindowsAudioEndPoint pass wrong length encoded data.

**Comment by z791382465** [comment]
I succeed in sip call with G711, G722, G729 codec.
I think WindowsAudioEndPoint have two problems.

1. Can't correctly set parameter durationRtpUnits where call OnAudioSourceEncodedSample.
Maybe can fix like this.
`OnAudioSourceEncodedSample?.Invoke((uint)(pcm.Length * _audioFormatManager.SelectedFormat.RtpClockRate / _audioFormatManager.SelectedFormat.ClockRate), encodedSample);`

2. Use fixed sample rate(8KHz) to open audio capture device.
If use G722, it should be 16KHz.
I hardcode it for test. I don't have an elegant solution for now.

**Comment by z791382465** [comment]
> Using which packages ? SIPSorceryMedia.SDL2 or SIPSorceryMedia.Windows ? Both ?

I only use [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows).
