### ISSUE TITLE
[WebRtc Question] How to enable RTP packets Retransmission on receiver side

### ISSUE THREAD

**Issue by mikhaylo1** [sipsorcery-org/sipsorcery#747]
Hi,

I use Sipsorcery to one-way receive WebRtc media from Chrome.
I managed successfully getting RTP and RTCP packets from Chrome and sending back RTCPCompoundPacket generated by my code

`peerConnection.SendRtcpReport(SDPMediaTypesEnum.video,new RTCPCompoundPacket(rtcpData));`

I can confirm Chrome successfully receives and recognizes my RTCPCompoundPacket packets
<img width="1207" alt="rtcpPacketlost" src="https://user-images.githubusercontent.com/18460856/171992519-4bf6f81b-bd13-46bf-8502-3ece3cef8c75.png">

However for a some reason Chrome does't generate Retransmitted packets when there is a massive packet lost and RTCPCompoundPacket with packets lost being send

<img width="1213" alt="noRetransmitedPackets" src="https://user-images.githubusercontent.com/18460856/171992612-944e054e-4805-4691-af26-9d5a8754da14.png">

I can confirm the same setup, but using another receiver (not Sipsorcery) forces Chrome to generate Retransmitted packets under the same conditions.

Do I need to enable something in Sipsorcery for allowing to receive these Retransmitted packets ? Or that functionality is not supported by Sipsorcery , or that is a problem with something else ?

Would appreciate your advise on that

**Comment by sipsorcery** [comment]
> Do I need to enable something in Sipsorcery for allowing to receive these Retransmitted packets ? Or that functionality is not supported by Sipsorcery , or that is a problem with something else ?

Typically you don't try and get big chunks of lost packets with realtime protocols like RTP. If you did manage to get the sender to resend the lost packets would you play them or the most recent packets?

Most audio codecs don't rely on previous packets for information and therefore don't need any special action to receover from lost packets. There will be an annoying gap in the audio stream during the period the packets are dropped but as soon as new packets arrive they will be usable.

Video is different due to the reliance on key frames to hold a sort of base information set that is needed to process all encoded packets up until the next key frame. Because key frames can be very large (>1MB) senders will often space them 30s or longer apart. When there's a large packet loss event for a video stream it will usualy be impossible to recover the correct video stream without getting a new key frame.

In your case I supsect requesting a new key frame is exactly what will fix it for you. The logic in this library is sorely lacking in that department and it doesn't happen automatically. Instead your application will somehoe need to detect the packet loss and then generate an RTCP feedback report to request the sender to generate a key frame. Here's an [example](https://github.com/sipsorcery-org/sipsorcery/blob/d1a2f2bc18d3868ceefbd50ad4c1b076e0ed1392/examples/WebRTCExamples/SIPToWebRtcBridgeVideo/Program.cs#L245).

**Comment by mikhaylo1** [comment]
Thank you for the detailed response,

I use GStreamer for decoding video stream received by Sipsorcery. GStreamer generates for me proper RTCP packets which I pack to _RTCPCompoundPacket_ and send back with _peerConnection.SendRtcpReport(SDPMediaTypesEnum.video,new RTCPCompoundPacket(rtcpData));_ 

I was hoping that would be enough to force Chrome sending Retransmited packets when there is a packets loss. I am aware about the [example](https://github.com/sipsorcery-org/sipsorcery/blob/d1a2f2bc18d3868ceefbd50ad4c1b076e0ed1392/examples/WebRTCExamples/SIPToWebRtcBridgeVideo/Program.cs#L245) you mentioned, but is it really necessary to manually send a PLI report if I already have a proper RTCP communication ?

**Comment by mikhaylo1** [comment]
the problem was related to probably incorrect/not full RTCP packets serialization in Sipsorcery. 
With #773 I can now send a non altered raw RTCP packets and Chrome packets lost retransmission is now working
