### ISSUE TITLE
Is it possible multistream PeerConnections with Sipsorcery

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#755]
since Janus now supports multistream PeerConnections, subscriptions can be done either in "bulks" (you use a single PeerConnection to subscribe to multiple streams from one or more publishers) or separately (each PeerConnections represents a subscription to a single publisher).

Is it possible to subscribe in bulks with a single PeerConnection with SipSorcery?

**Comment by ChristopheI** [comment]
Now in master branch and since release v6.0.8, it's possible to have on the same PeerConnection several Audio stream and/or several Video stream.

To manage them you have access to this new objects / events:

- PeerConnection.AudioStreamList
- PeerConnection.VideoStreamList
- PeerConnection.OnAudioFormatsNegotiatedByIndex
- PeerConnection.OnVideoFormatsNegotiatedByIndex
- PeerConnection.OnVideoFrameReceivedByIndex
- PeerConnection.OnRtpPacketReceivedByIndex
- PeerConnection.OnRtpEventByIndex

**Comment by mail2mhossain** [comment]
Thank you very much. Just upgraded from 6.0.6 to 6.0.8.

Trying to implement this.

BTW: do you have any example in source?
