### ISSUE TITLE
SipSorcery with .Net MAUI

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#778]
Is there any Audio/Video library that we can use with .Net MAUI + Sipsorcery

**Comment by ChristopheI** [comment]
I assume you want to target the same platforms as .Net MAUI.

I have updated/created these packages and tested well on Linux, MacOS and Windows. :
- [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg)
- [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2)

They should also work on iOS and Android (maybe with some improvements) since FFmpeg and SDL2 are also available on those platforms but I've never tried.

**Comment by farazp** [comment]
you assume these two lib but how can we using that can you make some sample code for this?

**Comment by headintheclouds21** [comment]
@farazp @ChristopheI Did either of you have any luck getting sipsorcery to work with .NET MAUI? I would like to implement it into my NET MAUI app and I'm wondering if it's possible

**Comment by hossam14102010** [comment]
@mail2mhossain Could you use [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg) and [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2) in .NET MAUI?

**Comment by mail2mhossain** [comment]
I have never tried with .NET MAUI. I am using it with AvaloniaUI.
