### ISSUE TITLE
SIPTCPChannel. TCP transfer fails if the server was not available at the time of first use.

### ISSUE THREAD

**Issue by alexpwnz** [sipsorcery-org/sipsorcery#868]
SIPTCPChannel  is using port for listened, but don't add it connection if server not answer (not available). Next send can't create connection because the port busy.
![image](https://user-images.githubusercontent.com/6427448/203063157-7d1265f8-aa2f-412c-a295-4a1b11404f6d.png)

**Comment by sipsorcery** [comment]
I realise this answer is very later but just in case it's still relevant.

Is it possilbe the TCP connection is still in progress rather than timed out?

The SIPTCPChannel does not add a reocrd of a connection unless it is [successfully established](https://github.com/sipsorcery-org/sipsorcery/blob/de91be67f8c79d6fd67bb5b18a7f9f33bd9ba6f5/src/core/SIP/Channels/SIPTCPChannel.cs#L408) so it's not obvious why a failed connection attempt would prevent a subsequent attempt.
